default:
  golem_name: EducationDashboardGolem
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/Christopher.McNally/Documents/R Projects/EducationDashboardGolem
